### ISSUE TITLE
组件也有onLaunch生命周期方法吗

### ISSUE THREAD

**Issue by Dragon-Rider** [tvfe/wxpage-app#2]
header的js里有个onLaunch，感觉好像是多余的，也没有被调用

**Comment by Dragon-Rider** [comment]
另外方便加个微信交流一下嘛，谢谢：）  wechat：EragonJiang

**Comment by switer** [comment]
组件里的声明周期与 Page是对等的，这不应该阉割。此处应该是 onPageLaunch。
